name: check

on:
  push:
    branches:
      - main
      - release-**
  pull_request:
    branches:
      - main
      - release-**

jobs:
  resolve-modules:
    name: Resolve modules
    runs-on: ubuntu-latest
    outputs:
        modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: set-modules
        run: |
          MODULES=$(find . -mindepth 2 -maxdepth 2 -type f -name go.mod -printf '{"workdir":"%h"},')
          MODULES="[${MODULES%,}]" # remove trailing comma
          echo "modules=$MODULES" >> "$GITHUB_OUTPUT"
  check:
    needs: resolve-modules
    name: Go ${{ matrix.go }} / ${{ matrix.module.workdir }}
    runs-on: ubuntu-latest
    strategy:
        matrix:
            go: ["1.23.5"]
            module: ${{ fromJson(needs.resolve-modules.outputs.modules) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: "**/*.sum"

      - name: download dependencies
        run: |
            cd ${{ matrix.module.workdir }}
            go mod download

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          working-directory: ${{ matrix.module.workdir }}

      - name: build all artifacts
        run: |
            cd ${{ matrix.module.workdir }}
            go build ./...

      - name: test all artifacts
        run: |
            cd ${{ matrix.module.workdir }}
            go test ./...

      - name: check
        run: |
          if [ ! -z "`git status -s`" ]; then
            echo "Following files are not consistent with CI:"
            git status -s
            git diff
            exit 1
          fi
